// app/layout.tsx
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Provider as RadixTooltipProvider } from "@radix-ui/react-tooltip";
import AppProvider from "./_components/AppProvider"; // <- relative import

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={outfit.className}>
          <RadixTooltipProvider>
            <AppProvider>{children}</AppProvider>
          </RadixTooltipProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
