import React from 'react'
import { ExternalLink } from 'lucide-react'

const SHOWCASES = [
  {
    title: 'SaaS Landing Page',
    category: 'Landing Page',
    gradient: 'from-blue-500 to-cyan-400',
    mockLines: [3, 2, 4, 1],
  },
  {
    title: 'Portfolio Website',
    category: 'Portfolio',
    gradient: 'from-purple-500 to-pink-400',
    mockLines: [2, 4, 3, 2],
  },
  {
    title: 'Analytics Dashboard',
    category: 'Dashboard',
    gradient: 'from-orange-500 to-red-400',
    mockLines: [4, 2, 1, 3],
  },
  {
    title: 'E-Commerce Store',
    category: 'E-Commerce',
    gradient: 'from-green-500 to-emerald-400',
    mockLines: [2, 3, 4, 2],
  },
]

const DemoPreview = () => {
  return (
    <section id="showcase" className="py-24 bg-gray-50/50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-purple-50 text-purple-600 text-xs font-semibold uppercase tracking-wider mb-4">
            Showcase
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-4">
            Built with{' '}
            <span className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
              AI in Seconds
            </span>
          </h2>
          <p className="text-lg text-gray-600">
            Real examples of websites generated by our AI. Each took less than 60 seconds.
          </p>
        </div>

        {/* Showcase Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {SHOWCASES.map((item, index) => (
            <div
              key={index}
              className="group relative bg-white rounded-2xl overflow-hidden border border-gray-100 shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1"
            >
              {/* Mock browser preview */}
              <div className={`relative h-48 bg-gradient-to-br ${item.gradient} p-4`}>
                {/* Mini browser chrome */}
                <div className="bg-white/90 backdrop-blur rounded-lg h-full p-3 space-y-2 overflow-hidden">
                  <div className="flex gap-1 mb-2">
                    <div className="w-2 h-2 rounded-full bg-red-300" />
                    <div className="w-2 h-2 rounded-full bg-yellow-300" />
                    <div className="w-2 h-2 rounded-full bg-green-300" />
                  </div>
                  {item.mockLines.map((width, i) => (
                    <div
                      key={i}
                      className="h-2 bg-gray-200 rounded-full"
                      style={{ width: `${width * 25}%` }}
                    />
                  ))}
                  <div className="grid grid-cols-2 gap-1.5 mt-2">
                    <div className="h-10 bg-gray-100 rounded" />
                    <div className="h-10 bg-gray-100 rounded" />
                  </div>
                </div>

                {/* Hover overlay */}
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300 flex items-center justify-center">
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <div className="bg-white rounded-full p-3 shadow-lg">
                      <ExternalLink className="h-5 w-5 text-gray-700" />
                    </div>
                  </div>
                </div>
              </div>

              {/* Card content */}
              <div className="p-4">
                <div className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">
                  {item.category}
                </div>
                <h3 className="font-semibold text-gray-900">{item.title}</h3>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

export default DemoPreview
